probe:
  labelling_efficiency:
    ptype: numeric
    wtype: float_slider
    range: [0, 1, 0.1]
    nintervals: 2
  probe_distance_to_epitope:
    ptype: numeric
    wtype: float_slider
    range: [0, 300, 0.1]
    nintervals: 2
particle_structural_integrity:
  structural_integrity:
    ptype: numeric
    wtype: float_slider
    range: [0, 1, 0.05]
    nintervals: 4
  structural_integrity_small_cluster:
    ptype: numeric
    wtype: float_slider
    range: [0, 10000, 1]
    nintervals: 3
  structural_integrity_large_cluster:
    ptype: numeric
    wtype: float_slider
    range: [0, 10000, 1]
    nintervals: 3
virtual_sample:
  random_orientations:
    ptype: logical
    wtype: logical
  random_placing:
    ptype: logical
    wtype: logical
acquisition:
  exp_time:
    ptype: numeric
    wtype: float_slider
    range: [0, 0.01, 0.0001]
    nintervals: 2