probe:
  labelling_efficiency:
    ptype: numeric
    wtype: float_slider
    range: [0, 1, 0.1]
    nintervals: 2
  probe_distance_to_epitope:
    ptype: numeric
    wtype: float_slider
    range: [0, 300, 0.1]
    nintervals: 2
particle_defect:
  defect:
    ptype: numeric
    wtype: float_slider
    range: [0, 1, 0.05]
    nintervals: 4
  defect_small_cluster:
    ptype: numeric
    wtype: float_slider
    range: [0, 10000, 1]
    nintervals: 3
  defect_large_cluster:
    ptype: numeric
    wtype: float_slider
    range: [0, 10000, 1]
    nintervals: 3
virtual_sample:
  random_orientations:
    ptype: logical
    wtype: logical
  number_of_particles:
    ptype: numeric
    wtype: int_slider
    range: [1, 100, 1]
    nintervals: 1
  random_placing:
    ptype: logical
    wtype: logical
acquisition:
  exp_time:
    ptype: numeric
    wtype: float_slider
    range: [0, 0.01, 0.0001]
    nintervals: 2