target:
  type:
  value:
known_targets:
model:
  ID:
  format:
  database:
binding:
  efficiency:
  orientation:
  wobble_range:
    theta:
    phi:
  distance:
    to_target:
    between_targets:
  paratope:
conjugation_sites:
  target:
    type:
    value:
  efficiency:
  fluorophore:

