label_name: Mock_antibody
target:
  type:
  value:
known_targets:
  - Mock
model:
  ID: 1HZH
  format: CIF
  database: RCSB
binding:
  efficiency: 1
  orientation: [0,0,1]
  wobble_range:
    theta: 10
    phi:
  distance:
    to_target: 10
    between_targets: estimate
  paratope: EFSAKF
conjugation_sites:
  target:
    type: Atom_residue
    value:
      atoms: CA
      residues: LYS
  efficiency: 1
epitope: # for secondary
  target:
    type: Sequence
    value: LSPGK
  normals:
