label_name: Nanobody
target:
  type:
  value:
known_targets:
  - Mock
model:
  ID: 7MFV
  format: CIF
  database: RCSB
binding:
  efficiency: 1
  orientation: [0,0,1]
  wobble_range:
    theta:
    phi:
  distance:
    to_target: 10
    between_targets: estimate
  paratope: VYLQ 
conjugation_sites:
  target:
    type: Atom_residue
    value:
      atoms: CA
      residues: LYS
  efficiency: 1
epitope: # for secondary
  target:
    type: 
    value: 
  normals:
