volume_dimensions: # in nanometers
  X: 1000
  Y: 1000
  Z: 100
particles:
  copies: 1 
  positions:
    type: global
    value: random
  orientations:
    type: global
    value: random
  distance:
    type: centers
    minimum: