name: Widefield
scale: 1.0e-09
PSF:
  source: generate
  resolution:  # in nanometers, as standard deviations
    X: 130
    Y: 130
    Z: 400
  voxelsize: 10
depth: 1000  # in nanometers
detector:
  FOV_size: # in nanometers. Default unless changed 
    X: 1000
    Y: 1000
  pixelsize: 100 # in nanometers
  noise: 
    binomial: 0.9
    gaussian:
      mean: 0
      standard_dev: 3
    gain: 1 
    baselevel:
      mean: 400
      standard_dev: 1
    ADU: 1
  
  
    # no value is only poisson noise. Expected order of values
    # p (binomial), mean, standard deviation (gaussian), gain (gamma), mean, standard deviation (abaselevel), adu (conversion factor) 