[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "supra_molecular_simulator"
version = "2024.09.27"
description = ""
authors = [ "Dami√°n Martinez <jdmartinez@igc.gulbenkian.pt>", "Bruno Saraiva <bruno.msaraiva2@gmail.com>", "Ricardo Henriques <ricardo@henriqueslab.org>",]
readme = "README.md"
[[tool.poetry.packages]]
include = "supra_molecular_simulator"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
matplotlib = "^3.9.0"
scipy = "^1.13.1"
biopython = "^1.83"
plotly = "^5.22.0"
trimesh = "^4.4.0"
ipympl = "^0.9.4"
pyyaml = "^6.0.1"
tifffile = "^2024.5.22"
tqdm = "^4.66.4"
scikit-image = "^0.23.2"
requests = "^2.32.3"
ipykernel = "^6.29.5"

[tool.poetry.scripts]
download-structures = "supra_molecular_simulator.download:download_suggested_structures"

[tool.poetry.dependencies.easy-gui-jupyter]
git = "https://github.com/HenriquesLab/easy-gui-jupyter.git"

[tool.poetry.dependencies.easy-gui-prompt]
git = "https://github.com/HenriquesLab/easy-gui-prompt.git"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
ipykernel = "^6.29.4"
ruff = "^0.4.3"
lazydocs = "^0.4.8"
gptrepo = "^1.0.3"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"
pytest-xdist = "^3.6.1"
nbmake = "^1.5.3"
mypy = "^1.10.0"

[tool.ruff]
select = ["E501"]  # Ensure long-line rules are enabled