[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "supra_molecular_simulator"
version = "2024.06.06"
description = ""
authors = [ "Damian Martinez <jdmartinez@igc.gulbenkian.pt>", "Bruno Saraiva <bruno.msaraiva2@gmail.com>", "Ricardo Henriques <ricardo@henriqueslab.org>",]
readme = "README.md"
[[tool.poetry.packages]]
include = "supra_molecular_simulator"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dependencies.easy-gui-jupyter]
git = "https://github.com/HenriquesLab/easy-gui-jupyter.git"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.4"
pre-commit = "^3.7.1"
gptrepo = "^1.0.3"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"
pytest-xdist = "^3.6.1"
