model:
  ID: 3J3Y
  format: CIF
  database: RCSB
  title: Atomic-level structure of the entire HIV-1 capsid (186 hexamers + 12 pentamers)
structural_integrity:
  small_cluster: 20
  big_cluster: 100
  