name: STED_Thev2016
scale: 1.0e-09
PSF:
  source: generate
  resolution:  # in nanometers, as standard deviations
    X: 15
    Y: 15
    Z: 20
  voxelsize: 5
depth: 100  # in nanometers
detector:
  FOV_size: # in nanometers. Default unless changed 
    X: 1000
    Y: 1000
  pixelsize: 15 # in nanometers
  noise: 
    binomial: 0.8
    gaussian:
      mean: 0
      standard_dev: 1
    gain: 1 
    baselevel:
      mean: 0
      standard_dev: 1
    ADU: 1
  
  
    # no value is only poisson noise. Expected order of values
    # p (binomial), mean, standard deviation (gaussian), gain (gamma), mean, standard deviation (abaselevel), adu (conversion factor) 