label_name: HIV_capsid_p24_AB
target:
  type: Sequence
  value: SPRTLNA
known_targets:
  - 3J3Y
model:
  ID: 1HZH
  format: CIF
  database: RCSB
binding:
  efficiency: 1
  orientation:
  wobble_range:
    theta: 30
    phi:
  distance:
    to_target: 20
    between_targets: estimate  # "estimate" or float
  paratope: DEQLK  #EFSAKF
conjugation_sites:
  target:
    type: Atom_residue
    value:
      atoms: 
      - CA
      residues: 
      - LYS
  DoL:

