label_name: Linker
target:
  type:
  value:
known_targets:
  - Mock
model:
  ID:
  format:
  database:
binding:
  efficiency: 1
  orientation: [0,0,1]
  wobble_range:
    theta: 10
    phi:
  distance:
    to_target: 200
    between_targets:
  paratope:
conjugation_sites:
  target:
    type:
    value:
  efficiency:

