label_name: NPC_Nup96_Cterminal_direct
target:
  type: Sequence
  value: ELAVGSL
known_targets:
  - 7R5K
model:
  ID:
  format:
  database:
binding:
  efficiency: 1
  orientation:
  wobble_range:
    theta:
    phi:
  distance:
    to_target:
    between_targets:
  paratope:
conjugation_sites:
  target:
    type:
    value:
  DoL:

